# Generated by Django 4.1.5 on 2023-11-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=155)),
                ('subject', models.CharField(max_length=155)),
                ('textarea', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
