# Generated by Django 4.1.5 on 2023-11-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
